Fix number of quantisation buckets
amazon-science/chronos-forecasting pull request #182
Opened 2024-09-30 09:09 UTC by alvaropp

Fixes https://github.com/amazon-science/chronos-forecasting/issues/181.

Chronos' tokenizer has a vocabulary size of n_tokens. Among these, there are n_special_tokens reserved for EOS, PAD, etc. and n_tokens - n_special_tokens allocated to numerical values. However, the provided MeanScaleUniformBins tokenizer creates n_tokens - n_special_tokens + 1 different buckets, resulting in a total of n_tokens + 1 possible tokens. This causes training and inference errors when one of the data points gets allocated to the largest bucket, as the model requires 0 <= token_id < n_tokens.

This PR modifies the `MeanScaleUniformBins` tokenizer, so that it creates one less bucket for numerical values.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-01 09:15 UTC, lostella commented
@alvaropp thanks for spotting this! I think that changing the values associated with tokens may not be the right way to go, since this will make the code diverge from how the model was originally trained. It's true that the additional buckets create an off-by-one issue and an invalid token ID (the tokenizer might have been simpler in these regards) but I think maybe the best fix is to clip the token ids in `_input_transform` before returning.

```
token_ids.clamp_(0, self.config.n_tokens - 1)
```

Let me know what you think!

2024-10-01 09:29 UTC, alvaropp commented
Hi, I think you're right, didn't think of that problem 😄 

I guess the clipping approach you propose would flatten big spikes by effectively putting normalised values that are around +15 and >1e20 in the same bucket (using default parameters for the tokenizer), but I reckon this should only be the case for time series samples with extreme values, and quite minor overall.

2024-10-01 16:52 UTC, alvaropp commented
@lostella ready for review now

2024-10-02 13:30 UTC, lostella requested changes
@alvaropp just suggesting to remove the comments, especially since they cross-reference each other. I think the explanation in the tests is sufficient.

2024-10-02 13:30 UTC, lostella commented on src/chronos/chronos.py
> +            # trained models.
```suggestion
            config.n_tokens
            - config.n_special_tokens
            - 1,
```

2024-10-02 13:30 UTC, lostella commented on src/chronos/chronos.py
> +
```suggestion
        token_ids.clamp_(0, self.config.n_tokens - 1)

```

2024-10-04 10:11 UTC, alvaropp commented
@lostella sure, removed.

2024-10-04 18:03 UTC, lostella commented on CITATION.cff
> +cff-version: 1.2.1
Just realized this is unrelated to the package change

```suggestion
cff-version: 1.2.0
```

2024-10-04 18:04 UTC, lostella commented on src/chronos/chronos.py
> +            - 1,
```suggestion
            config.n_tokens - config.n_special_tokens - 1,
```

2024-10-04 18:05 UTC, lostella approved these changes
Thanks @alvaropp!

2024-10-04 21:00 UTC, merged